# Generated by Django 6.0.3 on 2026-05-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_departments_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
