from django.db import migrations

# (code, name, units, year_level, semester)
SUBJECTS = {
    ('DCS', 'BSIT'): [
        ('IT101', 'Computer Fundamentals and Logic', 3, '1', '1st'),
        ('IT102', 'Computer Programming 1', 3, '1', '1st'),
        ('IT103', 'Mathematics in the Modern World', 3, '1', '1st'),
        ('IT104', 'Understanding the Self', 3, '1', '1st'),
        ('IT105', 'Readings in Philippine History', 3, '1', '1st'),
        ('IT106', 'Physical Education 1', 2, '1', '1st'),
        ('IT111', 'Computer Programming 2', 3, '1', '2nd'),
        ('IT112', 'Data Structures and Algorithms', 3, '1', '2nd'),
        ('IT113', 'Purposive Communication', 3, '1', '2nd'),
        ('IT114', 'Art Appreciation', 3, '1', '2nd'),
        ('IT115', 'Ethics', 3, '1', '2nd'),
        ('IT116', 'Physical Education 2', 2, '1', '2nd'),
        ('IT201', 'Object-Oriented Programming', 3, '2', '1st'),
        ('IT202', 'Database Management Systems', 3, '2', '1st'),
        ('IT203', 'Web Development 1', 3, '2', '1st'),
        ('IT204', 'Computer Networks', 3, '2', '1st'),
        ('IT205', 'Discrete Mathematics', 3, '2', '1st'),
        ('IT206', 'Physical Education 3', 2, '2', '1st'),
        ('IT211', 'Web Development 2', 3, '2', '2nd'),
        ('IT212', 'Systems Analysis and Design', 3, '2', '2nd'),
        ('IT213', 'Operating Systems', 3, '2', '2nd'),
        ('IT214', 'Information Assurance and Security', 3, '2', '2nd'),
        ('IT215', 'The Contemporary World', 3, '2', '2nd'),
        ('IT216', 'Physical Education 4', 2, '2', '2nd'),
        ('IT301', 'Software Engineering', 3, '3', '1st'),
        ('IT302', 'Mobile Application Development', 3, '3', '1st'),
        ('IT303', 'Human-Computer Interaction', 3, '3', '1st'),
        ('IT304', 'Advanced Database Management', 3, '3', '1st'),
        ('IT305', 'IT Elective 1', 3, '3', '1st'),
        ('IT311', 'Systems Integration and Architecture', 3, '3', '2nd'),
        ('IT312', 'Network Administration', 3, '3', '2nd'),
        ('IT313', 'Integrative Programming Technologies', 3, '3', '2nd'),
        ('IT314', 'Technopreneurship', 3, '3', '2nd'),
        ('IT315', 'IT Elective 2', 3, '3', '2nd'),
        ('IT401', 'Capstone Project 1', 3, '4', '1st'),
        ('IT402', 'IT Elective 3', 3, '4', '1st'),
        ('IT403', 'Social and Professional Issues in IT', 3, '4', '1st'),
        ('IT404', 'Practicum Preparation', 1, '4', '1st'),
        ('IT411', 'Capstone Project 2', 3, '4', '2nd'),
        ('IT412', 'Practicum / On-the-Job Training', 6, '4', '2nd'),
    ],
    ('DCS', 'BSCS'): [
        ('CS101', 'Introduction to Computing', 3, '1', '1st'),
        ('CS102', 'Computer Programming 1', 3, '1', '1st'),
        ('CS103', 'Calculus 1', 3, '1', '1st'),
        ('CS104', 'Understanding the Self', 3, '1', '1st'),
        ('CS105', 'Readings in Philippine History', 3, '1', '1st'),
        ('CS106', 'Physical Education 1', 2, '1', '1st'),
        ('CS111', 'Computer Programming 2', 3, '1', '2nd'),
        ('CS112', 'Discrete Mathematics', 3, '1', '2nd'),
        ('CS113', 'Calculus 2', 3, '1', '2nd'),
        ('CS114', 'Purposive Communication', 3, '1', '2nd'),
        ('CS115', 'Ethics', 3, '1', '2nd'),
        ('CS116', 'Physical Education 2', 2, '1', '2nd'),
        ('CS201', 'Data Structures and Algorithms', 3, '2', '1st'),
        ('CS202', 'Object-Oriented Programming', 3, '2', '1st'),
        ('CS203', 'Linear Algebra', 3, '2', '1st'),
        ('CS204', 'Computer Organization and Architecture', 3, '2', '1st'),
        ('CS205', 'Logic Design and Digital Circuits', 3, '2', '1st'),
        ('CS206', 'Physical Education 3', 2, '2', '1st'),
        ('CS211', 'Algorithm Design and Analysis', 3, '2', '2nd'),
        ('CS212', 'Operating Systems', 3, '2', '2nd'),
        ('CS213', 'Database Systems', 3, '2', '2nd'),
        ('CS214', 'Statistics for Computer Science', 3, '2', '2nd'),
        ('CS215', 'The Contemporary World', 3, '2', '2nd'),
        ('CS216', 'Physical Education 4', 2, '2', '2nd'),
        ('CS301', 'Software Engineering', 3, '3', '1st'),
        ('CS302', 'Theory of Automata and Formal Languages', 3, '3', '1st'),
        ('CS303', 'Artificial Intelligence', 3, '3', '1st'),
        ('CS304', 'Computer Networks', 3, '3', '1st'),
        ('CS305', 'CS Elective 1', 3, '3', '1st'),
        ('CS311', 'Machine Learning', 3, '3', '2nd'),
        ('CS312', 'Compiler Design', 3, '3', '2nd'),
        ('CS313', 'Parallel and Distributed Computing', 3, '3', '2nd'),
        ('CS314', 'Research Methods in CS', 3, '3', '2nd'),
        ('CS315', 'CS Elective 2', 3, '3', '2nd'),
        ('CS401', 'Thesis Writing 1', 3, '4', '1st'),
        ('CS402', 'CS Elective 3', 3, '4', '1st'),
        ('CS403', 'Professional Issues in Computing', 3, '4', '1st'),
        ('CS404', 'Practicum Preparation', 1, '4', '1st'),
        ('CS411', 'Thesis Writing 2', 3, '4', '2nd'),
        ('CS412', 'Practicum / Internship', 6, '4', '2nd'),
    ],
    ('DCS', 'BSCpE'): [
        ('CPE101', 'Engineering Drawing', 3, '1', '1st'),
        ('CPE102', 'Computer Programming 1', 3, '1', '1st'),
        ('CPE103', 'Calculus 1', 3, '1', '1st'),
        ('CPE104', 'Physics for Engineers 1', 3, '1', '1st'),
        ('CPE105', 'Understanding the Self', 3, '1', '1st'),
        ('CPE106', 'Physical Education 1', 2, '1', '1st'),
        ('CPE111', 'Engineering Mathematics 2', 3, '1', '2nd'),
        ('CPE112', 'Physics for Engineers 2', 3, '1', '2nd'),
        ('CPE113', 'Circuit Theory 1', 3, '1', '2nd'),
        ('CPE114', 'Computer Programming 2', 3, '1', '2nd'),
        ('CPE115', 'Purposive Communication', 3, '1', '2nd'),
        ('CPE116', 'Physical Education 2', 2, '1', '2nd'),
        ('CPE201', 'Logic Circuits and Switching Theory', 3, '2', '1st'),
        ('CPE202', 'Electronics 1', 3, '2', '1st'),
        ('CPE203', 'Signals and Systems', 3, '2', '1st'),
        ('CPE204', 'Data Structures', 3, '2', '1st'),
        ('CPE205', 'Engineering Economics', 3, '2', '1st'),
        ('CPE206', 'Physical Education 3', 2, '2', '1st'),
        ('CPE211', 'Electronics 2', 3, '2', '2nd'),
        ('CPE212', 'Microprocessor Systems', 3, '2', '2nd'),
        ('CPE213', 'Computer Architecture and Organization', 3, '2', '2nd'),
        ('CPE214', 'Digital Signal Processing', 3, '2', '2nd'),
        ('CPE215', 'The Contemporary World', 3, '2', '2nd'),
        ('CPE216', 'Physical Education 4', 2, '2', '2nd'),
        ('CPE301', 'Embedded Systems', 3, '3', '1st'),
        ('CPE302', 'Computer Networks', 3, '3', '1st'),
        ('CPE303', 'Operating Systems', 3, '3', '1st'),
        ('CPE304', 'VLSI Design', 3, '3', '1st'),
        ('CPE305', 'CPE Elective 1', 3, '3', '1st'),
        ('CPE311', 'Computer Control Systems', 3, '3', '2nd'),
        ('CPE312', 'Wireless Communications', 3, '3', '2nd'),
        ('CPE313', 'Software Engineering', 3, '3', '2nd'),
        ('CPE314', 'Research Methods in Engineering', 3, '3', '2nd'),
        ('CPE315', 'CPE Elective 2', 3, '3', '2nd'),
        ('CPE401', 'Capstone Design 1', 3, '4', '1st'),
        ('CPE402', 'CPE Elective 3', 3, '4', '1st'),
        ('CPE403', 'Engineering and Society', 3, '4', '1st'),
        ('CPE404', 'Practicum Preparation', 1, '4', '1st'),
        ('CPE411', 'Capstone Design 2', 3, '4', '2nd'),
        ('CPE412', 'Practicum / On-the-Job Training', 6, '4', '2nd'),
    ],
    ('DCCJE', 'BSCrim'): [
        ('CRIM101', 'Introduction to Criminology', 3, '1', '1st'),
        ('CRIM102', 'Criminal Law Book 1', 3, '1', '1st'),
        ('CRIM103', 'Mathematics in the Modern World', 3, '1', '1st'),
        ('CRIM104', 'Understanding the Self', 3, '1', '1st'),
        ('CRIM105', 'Readings in Philippine History', 3, '1', '1st'),
        ('CRIM106', 'Physical Education 1', 2, '1', '1st'),
        ('CRIM111', 'Criminal Law Book 2', 3, '1', '2nd'),
        ('CRIM112', 'Law Enforcement Administration', 3, '1', '2nd'),
        ('CRIM113', 'Purposive Communication', 3, '1', '2nd'),
        ('CRIM114', 'Ethics', 3, '1', '2nd'),
        ('CRIM115', 'Philippine Constitution', 3, '1', '2nd'),
        ('CRIM116', 'Physical Education 2', 2, '1', '2nd'),
        ('CRIM201', 'Criminalistics 1', 3, '2', '1st'),
        ('CRIM202', 'Criminal Sociology', 3, '2', '1st'),
        ('CRIM203', 'Legal Medicine', 3, '2', '1st'),
        ('CRIM204', 'Criminal Investigation', 3, '2', '1st'),
        ('CRIM205', 'Human Behavior and Crisis Management', 3, '2', '1st'),
        ('CRIM206', 'Physical Education 3', 2, '2', '1st'),
        ('CRIM211', 'Criminalistics 2', 3, '2', '2nd'),
        ('CRIM212', 'Correction and Rehabilitation', 3, '2', '2nd'),
        ('CRIM213', 'Traffic Management', 3, '2', '2nd'),
        ('CRIM214', 'Police Planning and Operations', 3, '2', '2nd'),
        ('CRIM215', 'The Contemporary World', 3, '2', '2nd'),
        ('CRIM216', 'Physical Education 4', 2, '2', '2nd'),
        ('CRIM301', 'Questioned Documents Examination', 3, '3', '1st'),
        ('CRIM302', 'Ballistics Examination', 3, '3', '1st'),
        ('CRIM303', 'Polygraph Examination', 3, '3', '1st'),
        ('CRIM304', 'Fingerprint Examination', 3, '3', '1st'),
        ('CRIM305', 'Criminal Jurisprudence', 3, '3', '1st'),
        ('CRIM311', 'Comparative Police Systems', 3, '3', '2nd'),
        ('CRIM312', 'Special Crimes Investigation', 3, '3', '2nd'),
        ('CRIM313', 'Crime Prevention and Control', 3, '3', '2nd'),
        ('CRIM314', 'Research Methods in Criminology', 3, '3', '2nd'),
        ('CRIM315', 'Penology', 3, '3', '2nd'),
        ('CRIM401', 'Thesis Writing 1', 3, '4', '1st'),
        ('CRIM402', 'Professional Development', 3, '4', '1st'),
        ('CRIM403', 'Community Relations', 3, '4', '1st'),
        ('CRIM404', 'Practicum Preparation', 1, '4', '1st'),
        ('CRIM411', 'Thesis Writing 2', 3, '4', '2nd'),
        ('CRIM412', 'Practicum / Field Work', 6, '4', '2nd'),
    ],
    ('DGTT', 'BEEd'): [
        ('BEED101', 'Child and Adolescent Development', 3, '1', '1st'),
        ('BEED102', 'Foundations of Education', 3, '1', '1st'),
        ('BEED103', 'Mathematics in the Modern World', 3, '1', '1st'),
        ('BEED104', 'Understanding the Self', 3, '1', '1st'),
        ('BEED105', 'Readings in Philippine History', 3, '1', '1st'),
        ('BEED106', 'Physical Education 1', 2, '1', '1st'),
        ('BEED111', 'The Child Learner', 3, '1', '2nd'),
        ('BEED112', 'Field Study 1', 3, '1', '2nd'),
        ('BEED113', 'Purposive Communication', 3, '1', '2nd'),
        ('BEED114', 'Art Appreciation', 3, '1', '2nd'),
        ('BEED115', 'Ethics', 3, '1', '2nd'),
        ('BEED116', 'Physical Education 2', 2, '1', '2nd'),
        ('BEED201', 'Teaching Mathematics in Elementary', 3, '2', '1st'),
        ('BEED202', 'Teaching Science in Elementary', 3, '2', '1st'),
        ('BEED203', 'Teaching English in Elementary', 3, '2', '1st'),
        ('BEED204', 'Teaching Filipino in Elementary', 3, '2', '1st'),
        ('BEED205', 'Educational Technology', 3, '2', '1st'),
        ('BEED206', 'Physical Education 3', 2, '2', '1st'),
        ('BEED211', 'Teaching Social Studies in Elementary', 3, '2', '2nd'),
        ('BEED212', 'Teaching Music, Arts and Physical Education', 3, '2', '2nd'),
        ('BEED213', 'Teaching Values Education', 3, '2', '2nd'),
        ('BEED214', 'Curriculum Design and Development', 3, '2', '2nd'),
        ('BEED215', 'The Contemporary World', 3, '2', '2nd'),
        ('BEED216', 'Physical Education 4', 2, '2', '2nd'),
        ('BEED301', 'Assessment of Learning', 3, '3', '1st'),
        ('BEED302', 'Facilitating Learner-Centered Teaching', 3, '3', '1st'),
        ('BEED303', 'The Teaching Profession', 3, '3', '1st'),
        ('BEED304', 'Field Study 2', 3, '3', '1st'),
        ('BEED305', 'Special Education', 3, '3', '1st'),
        ('BEED311', 'Classroom Management', 3, '3', '2nd'),
        ('BEED312', 'Research in Education 1', 3, '3', '2nd'),
        ('BEED313', 'Mother Tongue-Based Multilingual Education', 3, '3', '2nd'),
        ('BEED314', 'Guidance and Counseling', 3, '3', '2nd'),
        ('BEED315', 'Educ Elective 1', 3, '3', '2nd'),
        ('BEED401', 'Practice Teaching 1', 6, '4', '1st'),
        ('BEED402', 'Research in Education 2', 3, '4', '1st'),
        ('BEED411', 'Practice Teaching 2', 6, '4', '2nd'),
        ('BEED412', 'Thesis Writing', 3, '4', '2nd'),
    ],
    ('DGTT', 'BSEd'): [
        ('BSED101', 'Child and Adolescent Development', 3, '1', '1st'),
        ('BSED102', 'Foundations of Secondary Education', 3, '1', '1st'),
        ('BSED103', 'Mathematics in the Modern World', 3, '1', '1st'),
        ('BSED104', 'Understanding the Self', 3, '1', '1st'),
        ('BSED105', 'Readings in Philippine History', 3, '1', '1st'),
        ('BSED106', 'Physical Education 1', 2, '1', '1st'),
        ('BSED111', 'The Adolescent Learner', 3, '1', '2nd'),
        ('BSED112', 'Field Study 1', 3, '1', '2nd'),
        ('BSED113', 'Purposive Communication', 3, '1', '2nd'),
        ('BSED114', 'Art Appreciation', 3, '1', '2nd'),
        ('BSED115', 'Ethics', 3, '1', '2nd'),
        ('BSED116', 'Physical Education 2', 2, '1', '2nd'),
        ('BSED201', 'Content and Pedagogy 1 (Major)', 3, '2', '1st'),
        ('BSED202', 'Content and Pedagogy 2 (Major)', 3, '2', '1st'),
        ('BSED203', 'Educational Technology', 3, '2', '1st'),
        ('BSED204', 'Curriculum Design and Development', 3, '2', '1st'),
        ('BSED205', 'Assessment of Learning', 3, '2', '1st'),
        ('BSED206', 'Physical Education 3', 2, '2', '1st'),
        ('BSED211', 'Content and Pedagogy 3 (Major)', 3, '2', '2nd'),
        ('BSED212', 'Content and Pedagogy 4 (Major)', 3, '2', '2nd'),
        ('BSED213', 'Facilitating Learner-Centered Teaching', 3, '2', '2nd'),
        ('BSED214', 'Classroom Management', 3, '2', '2nd'),
        ('BSED215', 'The Contemporary World', 3, '2', '2nd'),
        ('BSED216', 'Physical Education 4', 2, '2', '2nd'),
        ('BSED301', 'The Teaching Profession', 3, '3', '1st'),
        ('BSED302', 'Content and Pedagogy 5 (Major)', 3, '3', '1st'),
        ('BSED303', 'Field Study 2', 3, '3', '1st'),
        ('BSED304', 'Research in Education', 3, '3', '1st'),
        ('BSED305', 'Special Education', 3, '3', '1st'),
        ('BSED311', 'Content and Pedagogy 6 (Major)', 3, '3', '2nd'),
        ('BSED312', 'Guidance and Counseling', 3, '3', '2nd'),
        ('BSED313', 'Mother Tongue-Based Instruction', 3, '3', '2nd'),
        ('BSED314', 'Educ Research Seminar', 3, '3', '2nd'),
        ('BSED315', 'Educ Elective 1', 3, '3', '2nd'),
        ('BSED401', 'Practice Teaching 1', 6, '4', '1st'),
        ('BSED402', 'Research Writing in Education', 3, '4', '1st'),
        ('BSED411', 'Practice Teaching 2', 6, '4', '2nd'),
        ('BSED412', 'Thesis Writing', 3, '4', '2nd'),
    ],
    ('DBM', 'BSBA'): [
        ('BA101', 'Business Organization and Management', 3, '1', '1st'),
        ('BA102', 'Principles of Economics', 3, '1', '1st'),
        ('BA103', 'Mathematics in the Modern World', 3, '1', '1st'),
        ('BA104', 'Understanding the Self', 3, '1', '1st'),
        ('BA105', 'Readings in Philippine History', 3, '1', '1st'),
        ('BA106', 'Physical Education 1', 2, '1', '1st'),
        ('BA111', 'Business Communication', 3, '1', '2nd'),
        ('BA112', 'Financial Accounting 1', 3, '1', '2nd'),
        ('BA113', 'Purposive Communication', 3, '1', '2nd'),
        ('BA114', 'Ethics', 3, '1', '2nd'),
        ('BA115', 'Microeconomics', 3, '1', '2nd'),
        ('BA116', 'Physical Education 2', 2, '1', '2nd'),
        ('BA201', 'Financial Accounting 2', 3, '2', '1st'),
        ('BA202', 'Managerial Accounting', 3, '2', '1st'),
        ('BA203', 'Business Law', 3, '2', '1st'),
        ('BA204', 'Operations Management', 3, '2', '1st'),
        ('BA205', 'Business Statistics', 3, '2', '1st'),
        ('BA206', 'Physical Education 3', 2, '2', '1st'),
        ('BA211', 'Human Resource Management', 3, '2', '2nd'),
        ('BA212', 'Marketing Management', 3, '2', '2nd'),
        ('BA213', 'Cost Accounting', 3, '2', '2nd'),
        ('BA214', 'Macroeconomics', 3, '2', '2nd'),
        ('BA215', 'The Contemporary World', 3, '2', '2nd'),
        ('BA216', 'Physical Education 4', 2, '2', '2nd'),
        ('BA301', 'Strategic Management', 3, '3', '1st'),
        ('BA302', 'Financial Management', 3, '3', '1st'),
        ('BA303', 'Business Research Methods', 3, '3', '1st'),
        ('BA304', 'Management Information Systems', 3, '3', '1st'),
        ('BA305', 'BA Elective 1', 3, '3', '1st'),
        ('BA311', 'International Business', 3, '3', '2nd'),
        ('BA312', 'Investment Management', 3, '3', '2nd'),
        ('BA313', 'Project Management', 3, '3', '2nd'),
        ('BA314', 'Entrepreneurship', 3, '3', '2nd'),
        ('BA315', 'BA Elective 2', 3, '3', '2nd'),
        ('BA401', 'Business Thesis 1', 3, '4', '1st'),
        ('BA402', 'BA Elective 3', 3, '4', '1st'),
        ('BA403', 'Business Ethics and CSR', 3, '4', '1st'),
        ('BA404', 'Practicum Preparation', 1, '4', '1st'),
        ('BA411', 'Business Thesis 2', 3, '4', '2nd'),
        ('BA412', 'Practicum / On-the-Job Training', 6, '4', '2nd'),
    ],
    ('DBM', 'BSEntrep'): [
        ('ENT101', 'Entrepreneurial Mind', 3, '1', '1st'),
        ('ENT102', 'Economics for Entrepreneurs', 3, '1', '1st'),
        ('ENT103', 'Mathematics in the Modern World', 3, '1', '1st'),
        ('ENT104', 'Understanding the Self', 3, '1', '1st'),
        ('ENT105', 'Readings in Philippine History', 3, '1', '1st'),
        ('ENT106', 'Physical Education 1', 2, '1', '1st'),
        ('ENT111', 'Business Communication', 3, '1', '2nd'),
        ('ENT112', 'Financial Accounting 1', 3, '1', '2nd'),
        ('ENT113', 'Purposive Communication', 3, '1', '2nd'),
        ('ENT114', 'Ethics', 3, '1', '2nd'),
        ('ENT115', 'Business Law', 3, '1', '2nd'),
        ('ENT116', 'Physical Education 2', 2, '1', '2nd'),
        ('ENT201', 'Opportunity Seeking and Ideation', 3, '2', '1st'),
        ('ENT202', 'Business Planning and Development', 3, '2', '1st'),
        ('ENT203', 'Financial Management for Entrepreneurs', 3, '2', '1st'),
        ('ENT204', 'Marketing for Entrepreneurs', 3, '2', '1st'),
        ('ENT205', 'Operations Management', 3, '2', '1st'),
        ('ENT206', 'Physical Education 3', 2, '2', '1st'),
        ('ENT211', 'Social Entrepreneurship', 3, '2', '2nd'),
        ('ENT212', 'Innovation Management', 3, '2', '2nd'),
        ('ENT213', 'E-Commerce and Digital Marketing', 3, '2', '2nd'),
        ('ENT214', 'Feasibility Study', 3, '2', '2nd'),
        ('ENT215', 'The Contemporary World', 3, '2', '2nd'),
        ('ENT216', 'Physical Education 4', 2, '2', '2nd'),
        ('ENT301', 'Venture Capital and Financing', 3, '3', '1st'),
        ('ENT302', 'Brand Management', 3, '3', '1st'),
        ('ENT303', 'Supply Chain Management', 3, '3', '1st'),
        ('ENT304', 'Business Research Methods', 3, '3', '1st'),
        ('ENT305', 'Entrep Elective 1', 3, '3', '1st'),
        ('ENT311', 'Family Business Management', 3, '3', '2nd'),
        ('ENT312', 'Franchising', 3, '3', '2nd'),
        ('ENT313', 'International Entrepreneurship', 3, '3', '2nd'),
        ('ENT314', 'Creativity and Innovation', 3, '3', '2nd'),
        ('ENT315', 'Entrep Elective 2', 3, '3', '2nd'),
        ('ENT401', 'Entrepreneurship Thesis 1', 3, '4', '1st'),
        ('ENT402', 'Business Incubation', 3, '4', '1st'),
        ('ENT403', 'Professional Ethics', 3, '4', '1st'),
        ('ENT404', 'Practicum Preparation', 1, '4', '1st'),
        ('ENT411', 'Entrepreneurship Thesis 2', 3, '4', '2nd'),
        ('ENT412', 'Practicum / On-the-Job Training', 6, '4', '2nd'),
    ],
    ('DIT', 'BSIT-Ind'): [
        ('IND101', 'Technical Drawing and CAD', 3, '1', '1st'),
        ('IND102', 'Engineering Fundamentals', 3, '1', '1st'),
        ('IND103', 'Mathematics in the Modern World', 3, '1', '1st'),
        ('IND104', 'Understanding the Self', 3, '1', '1st'),
        ('IND105', 'Readings in Philippine History', 3, '1', '1st'),
        ('IND106', 'Physical Education 1', 2, '1', '1st'),
        ('IND111', 'Applied Mathematics', 3, '1', '2nd'),
        ('IND112', 'Physics for Technology', 3, '1', '2nd'),
        ('IND113', 'Purposive Communication', 3, '1', '2nd'),
        ('IND114', 'Ethics', 3, '1', '2nd'),
        ('IND115', 'Technical Communication', 3, '1', '2nd'),
        ('IND116', 'Physical Education 2', 2, '1', '2nd'),
        ('IND201', 'Manufacturing Processes', 3, '2', '1st'),
        ('IND202', 'Industrial Safety and Health', 3, '2', '1st'),
        ('IND203', 'Electrical Technology', 3, '2', '1st'),
        ('IND204', 'Electronics Technology', 3, '2', '1st'),
        ('IND205', 'Industrial Materials and Processes', 3, '2', '1st'),
        ('IND206', 'Physical Education 3', 2, '2', '1st'),
        ('IND211', 'Machine Elements and Design', 3, '2', '2nd'),
        ('IND212', 'Hydraulics and Pneumatics', 3, '2', '2nd'),
        ('IND213', 'Industrial Automation', 3, '2', '2nd'),
        ('IND214', 'Quality Control and Assurance', 3, '2', '2nd'),
        ('IND215', 'The Contemporary World', 3, '2', '2nd'),
        ('IND216', 'Physical Education 4', 2, '2', '2nd'),
        ('IND301', 'Production Management', 3, '3', '1st'),
        ('IND302', 'CNC Technology', 3, '3', '1st'),
        ('IND303', 'Industrial Design', 3, '3', '1st'),
        ('IND304', 'Welding Technology', 3, '3', '1st'),
        ('IND305', 'Tech Elective 1', 3, '3', '1st'),
        ('IND311', 'Instrumentation and Control', 3, '3', '2nd'),
        ('IND312', 'Maintenance Engineering', 3, '3', '2nd'),
        ('IND313', 'Industrial Research Methods', 3, '3', '2nd'),
        ('IND314', 'Entrepreneurship in Technology', 3, '3', '2nd'),
        ('IND315', 'Tech Elective 2', 3, '3', '2nd'),
        ('IND401', 'Capstone Project 1', 3, '4', '1st'),
        ('IND402', 'Tech Elective 3', 3, '4', '1st'),
        ('IND403', 'Professional Issues in Technology', 3, '4', '1st'),
        ('IND404', 'Practicum Preparation', 1, '4', '1st'),
        ('IND411', 'Capstone Project 2', 3, '4', '2nd'),
        ('IND412', 'Practicum / On-the-Job Training', 6, '4', '2nd'),
    ],
}


def seed_subjects(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    Program = apps.get_model('accounts', 'Program')
    Subject = apps.get_model('enrollment', 'Subject')

    for (dept_code, prog_code), subject_list in SUBJECTS.items():
        try:
            dept = Department.objects.get(code=dept_code)
            prog = Program.objects.get(code=prog_code, department=dept)
        except (Department.DoesNotExist, Program.DoesNotExist):
            continue
        for code, name, units, year_level, semester in subject_list:
            Subject.objects.get_or_create(
                code=code,
                defaults={
                    'name': name,
                    'units': units,
                    'department': dept,
                    'program': prog,
                    'year_level': year_level,
                    'semester': semester,
                },
            )


def delete_subjects(apps, schema_editor):
    Subject = apps.get_model('enrollment', 'Subject')
    all_codes = [
        code
        for subject_list in SUBJECTS.values()
        for code, *_ in subject_list
    ]
    Subject.objects.filter(code__in=all_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('accounts', '0002_seed_departments_programs'),
    ]

    operations = [
        migrations.RunPython(seed_subjects, delete_subjects),
    ]
