# Generated by Django 6.0.5 on 2026-05-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelim', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('midterm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pre_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('dropped', 'Dropped')], max_length=20)),
                ('school_year', models.CharField(default='2024-2025', max_length=20)),
                ('semester', models.CharField(default='1st', max_length=20)),
                ('date_encoded', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollment.enrollment')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.instructorprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollment.subject')),
            ],
            options={
                'unique_together': {('enrollment', 'subject')},
            },
        ),
    ]
